### ISSUE TITLE
Make Lagrangian Diags pip installable

### ISSUE THREAD

**Issue by VeckoTheGecko** [OceanParcels/Lagrangian_diags#76]
Currently we have code in `Diagnostics/Functions` which is imported into Jupyter notebooks. I think it would be better to restructure this so that we provide a package `diags` which is installable. This would mean that the notebooks don't have to be in the same folder as the `Functions` folder.

Installing the package would look like `pip install -e .` in development mode, or `pip install git+https://github.com/OceanParcels/Lagrangian_diags.git@v...` for those that really want to install it in non-development mode.

The main motivation of this is to make it more portable, and to reduce duplication of notebooks. I think that uploading the package to PyPI is beyond scope at this point.

Thoughts?

**Comment by LauraGomezNavarro** [comment]
@VeckoTheGecko thanks!
"This would mean that the notebooks don't have to be in the same folder as the Functions folder." I'm not sure this is necessary right now, in most notebooks this is used: sys.path.insert(0, home_folder + "Diagnostics/Functions/"), which should solve the problem (if i'm not forgetting anything), but i think not all notebooks implement it.

**Comment by VeckoTheGecko** [comment]
> in most notebooks this is used: sys.path.insert(0, home_folder + "Diagnostics/Functions/"),

Awesome, I didn't realise this. Closing :)
